### ISSUE TITLE
Feature: vue3 setup syntax sugar surpport, thanks~

### ISSUE THREAD

**Issue by shawn-yee** [FullStackFlamingo/vscode-vue-component-importer#10]
```vue
<template>
    <MyHeader />
</template>

<script lang="ts" setup>
import MyHeader from '@/components/MyHeader.vue';
</script>

**Comment by FullStackFlamingo** [comment]
Thanks for your question, and thanks for using this extension.

Looks like Vetur now does importing since [0.30.0](https://github.com/vuejs/vetur/releases/tag/v0.30.0), so I'll be deprecating this project, and I'll create a PR on vetur for `@/` and setup sytax sugar,  if I have time.
