### ISSUE TITLE
Import not always in the correct place

### ISSUE THREAD

**Issue by jameswragg** [FullStackFlamingo/vscode-vue-component-importer#2]
Handy extension, thanks!
Finding if I'm using `<style lang="scss">` and have an `@import` in that style block, the imports are placed next to that scss import, rather than in the script block.

**Comment by FullStackFlamingo** [comment]
Thanks for finding this bug! Restricted document analysis/alteration to the <script> block of a single file component. 

Version 0.0.5 going live
